### ISSUE TITLE
This does not work anymore. Anyone who's able to get it working?

### ISSUE THREAD

**Issue by harshit-budhraja** [PawanOsman/ChatGPT#144]
I tried both the self-hosted versions and also the one which is provided free of cost (after getting an API Key from discord).

**Comment by PawanOsman** [comment]
This project is not working anymore and needs an update. you can use our hosted models for free in the meantime. if you have issues with our hosted models you can join our discord server and we can help

**Comment by itzraf-lab** [comment]
> This project is not working anymore and needs an update. you can use our hosted models for free in the meantime. if you have issues with our hosted models you can join our discord server and we can help 

So you're basically telling people to join your discord instead of fixing the repo? and the model isn't even OpenAI's

**Comment by PawanOsman** [comment]
> > This project is not working anymore and needs an update. you can use our hosted models for free in the meantime. if you have issues with our hosted models you can join our discord server and we can help
> 
> So you're basically telling people to join your discord instead of fixing the repo? and the model isn't even OpenAI's

@itzraf-lab 
This project is open source. As I mentioned, I don't have time to fix it right now. Anyone is welcome to fix it, and we appreciate and thank anyone who creates a PR. While I'm already serving my model, I'm letting everyone use it for free. If you don't like it, that's your problem, I'm offering it for free. This isn't paid work. Instead of appreciating my efforts, you're expecting me to work for you and abandon my own projects just to fix this one?

as i said, i don't have time to fix this right now, if you have you're welcome to fix it.

**Comment by hrhv** [comment]
@itzraf-lab Since I couldn't find any working API, I decided to build one myself over a weekend. Here's the POC: https://t.ly/0nfaa

I'm also rolling out invites to a few early users to try it out. Link is in the post description.
