### ISSUE TITLE
You have already used an API key on this IP address

### ISSUE THREAD

**Issue by TarekMahran** [PawanOsman/ChatGPT#21]
Hi All,

I am trying to use the hosted API but I always get this message: You have already used an API key on this IP address myIP. I reset the api in discore Bot but again the message appears when I try the api as shown below:

Request:
curl --location 'https://api.pawan.krd/v1/completions' \
--header 'Authorization: Bearer pk-myapikey' \
--header 'Content-Type: application/json' \
--data '{
    "model": "text-davinci-003",
    "prompt": "Human: Hello\\nAI:",
    "temperature": 0.7,
    "max_tokens": 256,
    "stop": [
        "Human:",
        "AI:"
    ]
}'

Response:
{
    "status": false,
    "error": "You have already used an API key on this IP address myip",
    "hint": "You can get support from https://discord.pawan.krd",
    "info": "https://gist.github.com/PawanOsman/72dddd0a12e5829da664a43fc9b9cf9a",
    "support": "https://discord.pawan.krd"
}

**Comment by PawanOsman** [comment]
Hey, maybe you are using a shared hosting like replit or home internet,

when you are using shared hosting you don't have a dedicated IP address, and maybe someone else uses the same IP as you because its shared, and our hosted API doesn't support using 2 keys on the same IP address to prevent abuse usage
