### ISSUE TITLE
invalid_request_error

### ISSUE THREAD

**Issue by vip164** [PawanOsman/ChatGPT#76]
I'm using "http://localhost:3040/v1" as url but it alerts

{
    "status": false,
    "error": {
        "message": "The requested endpoint was not found. please make sure to use \"http://localhost:3040/v1\" as the base URL.",
        "type": "invalid_request_error"
    },
    "support": "https://discord.pawan.krd"
}

**Comment by PawanOsman** [comment]
If you're using the OpenAI Python library, you need to add an additional slash to the end of the base URL. Use `http://localhost:3040/v1/`.

**Comment by yangmiok** [comment]
> I'm using "http://localhost:3040/v1" as url but it alerts
> 
> { "status": false, "error": { "message": "The requested endpoint was not found. please make sure to use "[http://localhost:3040/v1\](http://localhost:3040/v1%5C)" as the base URL.", "type": "invalid_request_error" }, "support": "https://discord.pawan.krd" }

Have you fixed this issue?How was it fixed?

**Comment by demon2202** [comment]
@yangmiok @vip164 
In order to remove the error you just need to put back slash(\) at the end of the url [http://localhost:3040/v1/] WHENEVER U ARE using the [OpenAI Python library], you need to add an additional slash AT the end of the URL

If the problem still does not get solved make sure 
1- Ensure that you're using the correct path 
2-Ensure that there are no formatting errors in the URL
